/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vicman_jnitest_fragments_VideoFragment */

#ifndef _Included_com_vicman_jnitest_fragments_VideoFragment
#define _Included_com_vicman_jnitest_fragments_VideoFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vicman_jnitest_fragments_VideoFragment
 * Method:    passArray
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_vicman_jnitest_fragments_VideoFragment_passArray
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
